version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: zinter_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zinterdb
      MONGO_INITDB_ROOT_PASSWORD: MjMvbRqm6vvq45aI
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
