// <auto-generated />
using LogisticsSolution.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsSolution.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250310140732_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogisticsSolution.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ZN_Province", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drenthe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flevoland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Friesland (Fryslân)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gelderland"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Groningen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Limburg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Noord-Brabant"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Noord-Holland"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Overijssel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Utrecht"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Zeeland"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Zuid-Holland"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Assen"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lelystad"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Arnhem"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Groningen"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Maastricht"
                        },
                        new
                        {
                            Id = 18,
                            Name = "'s-Hertogenbosch (Den Bosch)"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Haarlem"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Zwolle"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Middelburg"
                        },
                        new
                        {
                            Id = 22,
                            Name = "The Hague (Den Haag)"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Leeuwarden"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
